# Generated by Django 4.2.9 on 2024-10-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Перейдите по этой ссылке, чтобы оплатить продукт",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.PositiveIntegerField(
                help_text="Введите сумму оплаты", verbose_name="Сумма оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличными"), ("bank_transfer", "Перевод на счет")],
                default="bank_transfer",
                help_text="Выберите способ оплаты",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
