# Generated by Django 4.2.9 on 2024-11-04 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите лайки",
                null=True,
                related_name="user_likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Лайки",
            ),
        ),
    ]
